// price_1MtvMSFrCY7e7e3NSzXuwvf0      cofee                these cofee, sungalasses and camera are also created on stripe and this is the id that was generated this can be done in the end 
// price_1MtvSbFrCY7e7e3NGMMEhPv6      sungalasses
// price_1MtvVzFrCY7e7e3NnAzt4XqB      camera




const ProdutcsArray = [

    {
        id: "price_1MtvMSFrCY7e7e3NSzXuwvf0",
        title: "Souris",
        price: 4.99,
        imageSrc: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1167&q=80"
    },
    {
        id: "price_1MtvSbFrCY7e7e3NGMMEhPv6 ",
        title: "Encre hp 302",
        price: 9.99,
        imageSrc: "https://media.auchan.fr/A0220170112000537293PRIMARY_512x512/B2CD/"
    },
    {
        id: "price_1MtvVzFrCY7e7e3NnAzt4XqB",
        title: "Tablette samsung",
        price: 139.99,
        imageSrc: "https://cdn.lesnumeriques.com/optim/produits/36/26915/samsung-galaxy-tab-e_5b9c69af8a471b5a__1200_1200__overflow.jpg"
    },
    {
        id: "price_fake1",
        title: "Ordinateur portable hp",
        price: 244.99,
        imageSrc: "https://www.hp.com/fr-fr/shop/Html/Merch/Images/c06927622_500x367.jpg"
    },
    {
        id: "price_fake2 ",
        title: "Enceinte Bleutooth",
        price: 41.99,
        imageSrc: "https://www.rueducommerce.fr/media/produits/wewoo/img//enceinte-bluetooth-e13-mini-portable-haut-parleur-sans-fil-stereo-radio-musique-subwoofer-haut-parleurs-colonne-avec-tf-fmrouge-noir-10553386-27409640_1140x1140.jpg"
    },
    {
        id: "price_fake3",
        title: "Sac ordinateur (homme)",
        price: 39.99,
        imageSrc: "https://e2r-paris.com/4566-product_large/sac-ordinateur-15-pouces-tissu-gris-et-cuir-homme-enzo.jpg"
    },


]


function GetProductData (id) {

    let ProductData = ProdutcsArray.find(product => product.id === id);

    if (ProductData === undefined){
        console.log("product data does not exist dor ID :" + id);
        return undefined

    }
    return ProductData;
}




export {ProdutcsArray, GetProductData};


// let create a const where are going to define all aour products let put this into an array so that we can later call it wit array.map()
// the id for each product is the link that is generated by stripe after a product is create so we can start by simply using numbers or we can directly create products and get the id
// the const GetProductData here will let us go to every product it is better to use .find instead of .map for this step